name: common ci
on: 
    workflow_call:
        inputs: 
            component_name:
                required: true
                type: string
jobs:
    Download-dependencies:
      runs-on: self-hosted
      steps:
        - name: check out code
          uses: actions/checkout@v4
        - run: echo build
    Test:
        runs-on: self-hosted
        needs: Download-dependencies
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - run: echo test
   
              