name: common ci
on: 
    workflow_call:
        inputs: 
            component_name:
                required: true
                type: string
jobs:
    Download-dependencies:
      runs-on: self-hosted
      steps:
        - name: check out code
          uses: actions/checkout@v4
        - run: echo build
    DockerBuild-n-Push:
      runs-on: self-hosted
      needs: Download-dependencies
      steps:
        - name: check out repo
          uses: actions/checkout@v4
        - run: echo tests

    Dev-Deployment:
        runs-on: self-hosted
        needs: DockerBuild-n-Push
        steps:
          - name: checkout code
            uses: actions/checkout@v4
            with:
                repository: Thippareddykishor/roboshop-helm
          - name: Deploy
            run: |
              aws eks update-kubeconfig --name dev
              make component=${{inputs.component_name}} env=dev
              