name: common ci
on: 
    workflow_call:
        inputs: 
            component_name:
                required: true
                type: string
            app_type:
                required: true
                type: string
jobs:
    Download-dependencies-docker-build:
      runs-on: self-hosted
      steps:
        - name: check out code
          uses: actions/checkout@v4
        - name: Download dependencies
          run: |
            if [ ${{inputs.app_type}} == nodejs ]; then
              npm install
            elif  [ ${{inputs.app_type}} == maven ]; then
              mvn package
            fi
            docker build -t 740279881161.dkr.ecr.us-east-1.amazonaws.com/cart:${GITHUB_SHA} .

    DockerPush:
      runs-on: self-hosted
      needs: Download-dependencies-docker-build
      steps:
        - name: check out repo
          uses: actions/checkout@v4
        - name: docker push
          run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 740279881161.dkr.ecr.us-east-1.amazonaws.com
            docker push 740279881161.dkr.ecr.us-east-1.amazonaws.com/cart:${GITHUB_SHA}            

    Dev-Deployment:
        runs-on: self-hosted
        needs: DockerPush
        steps:
          - name: checkout code
            uses: actions/checkout@v4
            with:
                repository: Thippareddykishor/roboshop-helm
          - name: Deploy
            run: |
              aws eks update-kubeconfig --name dev
              make component=${{inputs.component_name}} env=dev
              